Rozetka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False
)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

payment/urls.py
from django.urls import path
from . import views


app_name = 'payment'

urlpatterns = [
    path('process/', views.payment_view, name='process'),
    path('success/', views.payment_success, name='success'),
    path('error/', views.payment_error, name='error'),
]

cart/forms.py
from django import forms


class CartAddProductForm(forms.Form):
    # add-to-cart form
    quantity = forms.IntegerField(initial=1, widget=forms.HiddenInput)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from main.models import Category


@require_POST
def cart_add(request, product_id):
    # добавление продуктов в корзину
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    # удаление продуктов из корзины
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    # то что находится в корзине
    cart = Cart(request)
    categories = Category.objects.all()
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart, 'categories': categories})

cart/templates/cart/detail.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
Корзина покупок
{% endblock %}

{% block content %}

<h1>Корзина покупок</h1>
<table class="cart">
  <thead>
    <tr>
      <th>Картинка</th>
      <th>Товар</th>
      <th>Обновить кол-во</th>
      <th>Удалить</th>
      <th>Кол-во</th>
      <th>Цена за шт</th>
      <th>Общая стоимость</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
      {% with product=item.product %}
        <tr>
          <td>
            <a href="{{ product.get_absolute_url }}">
              <img src="{{ product.image.url }}" style="display: block; margin: 0 auto; width: 40px;">
            </a>
          </td>
          <td>{{ product.name }}</td>
          <td>
            <form action="{% url 'cart:cart_add' product.id %}" method="post">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.update }}
              <input type="submit" value="Обновить">
              {% csrf_token %}
            </form>
          </td>
          <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
          <td>
            {{ item.quantity }}
          </td>
          <td class="num">{{ item.price }}грн.</td>
          <td class="num">{{ item.total_price }}грн.</td>
        </tr>
      {% endwith %}
    {% endfor %}
    <tr class="total">
      <td>Всего</td>
      <td colspan="4"></td>
      <td class="num">{{ cart.get_total_price }} грн.</td>
    </tr>
  </tbody>
</table>
<p class="text-right">
  <a href="{% url 'main' %}" class="button light">В магазин</a>
  <a href="{% url 'payment:process' %}" class="button">Оформить заказ</a>
</p>
{% endblock %}