Rozetka/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path('', include('main.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    prefix_default_language=False
)

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

main/urls.py
from django.urls import path
from .import views


urlpatterns = [
    path('', views.WashingMachineView.as_view(), name='main'),
    path('search/', views.SearchViews.as_view(), name='search'),
    path('product/<slug:slug>/', views.DetailProductView.as_view(), name='detail'),
    path('category/<slug:cat_slug>/', views.CategoryOutputView.as_view(), name='category'),
    path('brand/<slug:brand_slug>/', views.BrandOutputView.as_view(), name='brand'),
    path('review/<int:pk>/', views.ReviewsView.as_view(), name='review'),
    path('add-rating/', views.AddStarsRating.as_view(), name='add_rating'),
    path('profile/', views.PersonalCabinetView.as_view(), name='profile'),
    path('compare/', views.CompareView.as_view(), name='compare'),

]

main/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Category(models.Model):
    # Category
    name = models.CharField('Название', max_length=200)
    image = models.ImageField('Иконки', upload_to='category_photo/')
    url = models.SlugField(max_length=200, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug' : self.url})


class Salesman(models.Model):
    # Salesman
    name = models.CharField('Имя', max_length=50)
    image = models.ImageField('Иконка', upload_to='salesman/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продавец'
        verbose_name_plural = 'Продавцы'


class Product(models.Model):
    # all items
    name = models.CharField('Название', max_length=300)
    code = models.IntegerField('Код товара', blank=True, null=True)
    series = models.CharField('Серия', max_length=100, blank=True, null=True)
    price = models.DecimalField('Цена', max_digits=10, decimal_places=2)
    display_size = models.CharField('Размер дисплея', max_length=50, blank=True, null=True)
    main_camera = models.CharField(
        'Основная камера', max_length=100, blank=True, null=True)
    battery_capacity = models.CharField('Ёмкость батареи', max_length=50, blank=True, null=True)
    CPU = models.CharField('Процессор', max_length=122, blank=True, null=True)
    ram = models.CharField('Оперативная память', max_length=50, blank=True, null=True)
    operating_system = models.CharField('Операционная система', max_length=50, blank=True, null=True)
    screen_refresh_rate = models.CharField(
        'Частота обновления экрана', max_length=30, blank=True, null=True)
    ram_type = models.CharField(
        'Тип оперативной памяти', max_length=20, blank=True, null=True)
    ssd_capacity = models.CharField(
        'Объём SSD', max_length=20, blank=True, null=True)
    spin_speed = models.CharField('Скорость отжима', max_length=50, blank=True, null=True)
    maximum_laundry_load = models.CharField('Загрузка', max_length=50, blank=True, null=True)
    color = models.CharField('Цвет', max_length=50, blank=True, null=True)
    weight = models.PositiveSmallIntegerField('Вес, кг', blank=True, null=True)
    fridge_capacity = models.PositiveSmallIntegerField(
        'Объем холодильной камеры, л', blank=True, null=True)
    image = models.ImageField('Фото', upload_to='Products_photo/')
    url = models.SlugField(max_length=200, unique=True)
    draft = models.BooleanField('Черновик', default=False)
    by_action = models.BooleanField('Акциооный товар', default=False) 
    brand = models.ForeignKey(
        'BrandProduct', on_delete=models.CASCADE, verbose_name='Марка товара', blank=True, null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name='Категория')
    salesman = models.ForeignKey(
        Salesman, on_delete=models.CASCADE, verbose_name='Продавец', blank=True, null=True
    )

    def __str__(self):
        return f"{self.brand} {self.name}"

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        ordering = ['name']

    def get_absolute_url(self):
        return reverse('detail', kwargs={'slug' : self.url})


class BrandProduct(models.Model):
    # Product brand
    title = models.CharField('Название', max_length=100)
    image = models.ImageField(upload_to='brand_images/')
    url = models.SlugField(max_length=15, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Марка товара'
        verbose_name_plural = 'Марки товаров'

    def get_absolute_url(self):
        return reverse('brand', kwargs={'brand_slug' : self.url})


class RatingsStar(models.Model):
    # Star Rating
    value = models.PositiveSmallIntegerField('Значение', default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = 'Звезда рейтинга'
        verbose_name_plural = 'Звезды рейтинга'
        ordering = ['-value']


class Rating(models.Model):
    # Rating
    ip = models.CharField('IP адресс', max_length=60)
    star = models.ForeignKey(
        RatingsStar, on_delete=models.CASCADE, verbose_name='Звезда')
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Товар')
    
    def __str__(self):
        return self.star

    class Meta:
        verbose_name = 'Рейтинг'
        verbose_name_plural = 'Рейтинги'
    

class Review(models.Model):
    # Review
    name = models.CharField('Имя', max_length=100)
    text = models.TextField('Коментарий', max_length=5000)
    email = models.EmailField()
    parent = models.ForeignKey(
        'self', on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Родитель'
    )
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, verbose_name='Товар')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class UserProfile(models.Model):
    # UserProfile
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name = 'Профиль пользователя'
        verbose_name_plural = 'Профили пользователей'

main/forms.py
from django import forms
from .models import *
from .models import UserProfile


class ReviewForm(forms.ModelForm):
    # Adding a comment
    class Meta:
        model = Review
        fields = (
            'name', 'text', 'email'
        )


class RatingForm(forms.ModelForm):
    # Add rating form
    star = forms.ModelChoiceField(
        queryset=RatingsStar.objects.all(), widget=forms.RadioSelect(),
        empty_label=None
    )

    class Meta:
        model = Rating
        fields = ('star',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['first_name', 'last_name', 'phone', 'profile_image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['profile_image'].widget.attrs['accept'] = 'user_images/'

main/views.py
from django.shortcuts import get_object_or_404, redirect, HttpResponse, render
from .models import *
from django.views.generic import ListView, DetailView, View
from django.db.models import Q
from .forms import *
from cart.forms import CartAddProductForm
from .tasks import send_email_task



class CategoryMixin:
    # Category output
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['category'] = Category.objects.all()
        context['brand'] = BrandProduct.objects.all()
        context['star_form'] = RatingForm()
        context['cart_product_form'] = CartAddProductForm
        return context


class WashingMachineView(CategoryMixin, ListView):
    # Output WashingMachine
    model = Product
    queryset = Product.objects.filter(draft=False)
    paginate_by = 5


class SearchViews(CategoryMixin, ListView):
    # Search products
    def get_queryset(self):
        query = self.request.GET.get('search')
        return Product.objects.filter(
            Q(name__icontains=query) | Q(code__icontains=query)
        )


class DetailProductView(CategoryMixin, DetailView):
    # Full product description
    model = Product
    slug_field = 'url'


class CategoryOutputView(CategoryMixin, ListView):
    # Product listing by category
    model = Product
    template_name = 'main/product_list.html'
    paginate_by = 5

    def get_queryset(self):
        category = get_object_or_404(Category, url=self.kwargs['cat_slug'])
        return Product.objects.filter(category=category, draft=False)


class BrandOutputView(CategoryMixin, ListView):
    # Brand output
    model = Product
    template_name = 'main/product_list.html'
    paginate_by = 5

    def get_queryset(self):
        brand = get_object_or_404(BrandProduct, url=self.kwargs['brand_slug'])
        return Product.objects.filter(brand=brand)


class ReviewsView(CategoryMixin, View):
    # Adding a comment
    def post(self, request, pk):
        form = ReviewForm(request.POST)
        product = Product.objects.get(id=pk)
        if form.is_valid():
            form = form.save(commit=False)
            form.product = product
            form.save()
        return redirect(product.get_absolute_url())


class AddStarsRating(View):
    # Adding a rating
    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[0]
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip

    def post(self, request):
        form = RatingForm(request.POST)
        if form.is_valid():
            Rating.objects.update_or_create(
                ip=self.get_client_ip(request),
                product_id=int(request.POST.get("product")),
                defaults={'star_id': int(request.POST.get("star"))}
            )
            return HttpResponse(status=201)
        else:
            return HttpResponse(status=400)


class PersonalCabinetView(View):
    # User profile
    def get(self, request):
        user = request.user
        profile, created = UserProfile.objects.get_or_create(user=user)
        form = UserProfileForm(instance=profile)
        context = {'form': form}
        return render(request, 'main/profile.html', context)

    def post(self, request):
        user = request.user
        profile, created = UserProfile.objects.get_or_create(user=user)
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile')
        context = {'form': form}
        return render(request, 'main/profile.html', context)


class CompareView(CategoryMixin, View):
    def get(self, request):
        product_ids = request.GET.getlist('product_ids')
        products = Product.objects.filter(id__in=product_ids)

        context = {'products': products}
        return render(request, 'main/compare.html', context)


def process_purchase(purchase_data):
    # Sending emails via Celery task
    subject = "Подтверждение покупки"
    message = "Спасибо за вашу покупку!"
    recipient_list = ['tpenep777@gmail.com']
    send_email_task.delay(subject, message, recipient_list)

main/templates/main/ElectronicsDevice_list.html
{% extends 'main/layout.html' %}
{% load static %}

{% block title %}
Интернет-магазин ROZETKA
{% endblock %}

{% block content %}
<!-- left conteiner start -->

<div class="main-wrapper">
	<div class="left-conteiner">
		{% for el in category %}
		<ul>
			<li>
				<a href="{{ el.get_absolute_url }}">
					{% if el.image %}
					<img src="{{ el.image.url }}" alt="iсon">
					{% endif %}
					{{ el.name }}
				</a>
			</li>
		</ul>
		{% endfor %}
		<hr>
	</div>

	<!-- left conteiner end -->


	<!-- right conteiner start -->

	<div class="main-content">
		<div class="image-slider">
			<div class="slider-controls">
				<div class="slider-control prev" onclick="prevSlide()">&#10094;</div>
				<div class="slider-control next" onclick="nextSlide()">&#10095;</div>
			</div>
			<img class="slider__img active" src="{% static 'main/img/11.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/12.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/13.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/15.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/16.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/17.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/18.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/19.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/20.jpg' %}" alt="slider_img">
			<img class="slider__img" src="{% static 'main/img/21.jpg' %}" alt="slider_img">
		</div>
	</div>
</div>

<!-- right conteiner end -->

<script>
	var indexValue = 0;
	var timer;

	function SlideShow() {
		timer = setTimeout(SlideShow, 3500)
		var x;
		const elements = document.querySelectorAll('.slider__img');
		for (x = 0; x < elements.length; x++) {
			elements[x].style.display = "none";
		}
		indexValue++;
		if (indexValue > elements.length) {
			indexValue = 1;
		}
		elements[indexValue - 1].style.display = "block";
	}
	SlideShow();

	function prevSlide() {
		clearTimeout(timer);
		const elements = document.querySelectorAll('.slider__img');
		if (indexValue == 1) {
			indexValue = elements.length;
		} else {
			indexValue--;
		}
		for (let i = 0; i < elements.length; i++) {
			elements[i].style.display = "none";
		}
		elements[indexValue - 1].style.display = "block";
	}

	function nextSlide() {
		clearTimeout(timer);
		const elements = document.querySelectorAll('.slider__img');
		if (indexValue == elements.length) {
			indexValue = 1;
		} else {
			indexValue++;
		}
		for (let i = 0; i < elements.length; i++) {
			elements[i].style.display = "none";
		}
		elements[indexValue - 1].style.display = "block";
	}
</script>

{% endblock %}

main/templates/main/compare.html
{% extends 'main/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
Сравнение товаров
{% endblock %}

{% block content %}
<h1>Сравнение товаров</h1>

{% if products %}
  <table>
    <thead>
      <tr>
        <th>{% trans 'Название' %}</th>
        <th>{% trans 'Цена' %}</th>
      </tr>
    </thead>
    <tbody>
      {% for product in products %}
        <tr>
          <td>{{ product.name }}</td>
          <td>{{ product.price }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% else %}
  <p>{% trans 'Нет выбранных товаров для сравнения' %}</p>
{% endif %}

{% endblock %}
w

main/templates/main/layout.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- bootstrap start -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <!-- bootstrap end -->
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <script src="{% static 'main/js/script_slider.js' %}"></script>
    <script src="{% static 'main/js/language-form.js' %}"></script>
    <script src="{% static 'main/js/brands-wrapper.js' %}"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <link rel="shortcut icon" href="{% static 'main/img/rozetka.png' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <header>
        <div class="img-header">
            <img src="https://content2.rozetka.com.ua/banner_header/image/original/330998888.jpg" alt="logo-up">
        </div>
        <div>
            <div class="container">
                <div class="header_logo">
                    <a href="{% url 'main' %}">
                        <img src="https://content2.rozetka.com.ua/widget_logotype/full/original/229862237.svg"
                            alt="logo-rozetka">
                    </a>
                </div>
                <div class="header_search">
                    <form action="{% url 'search' %}" method="GET">
                        <input type="search" name="search" placeholder="{% trans 'Я ищу...' %}">
                        <button class="btn btn-success" type="submit">{% trans 'Найти' %}</button>
                    </form>
                </div>
                <div class="header_nav">
                    <ul>
                        <form id="language-form" action="{% url 'set_language' %}" method="post">
                            {% csrf_token %}
                            <input name="next" type="hidden" value="{{ redirect_to }}">
                            <div class="styled-select">
                                <select id="language-select" name="language">
                                    {% get_current_language as LANGUAGE_CODE %}
                                    {% get_available_languages as LANGUAGES %}
                                    {% get_language_info_list for LANGUAGES as languages %}
                                    {% for language in languages %}
                                    <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE%}selected{%endif %}>
                                        {{ language.name_local }} ({{ language.code }})
                                    </option>
                                    {% endfor %}
                                </select>
                            </div>
                        </form>
                        {% if user.is_authenticated %}
                        <li class="nav-r"><a href="{% url 'profile' %}"><i class="bi bi-card-list"
                                    style="margin-left: 7px;"></i></a></li>
                        {% else %}
                        <li class="nav-r"><a href="{% url 'account_login' %}"><i class="bi bi-person"></i></a></li>
                        {% endif %}
                        <li class="nav-r"><a href="{% url 'compare' %}"><i
                                    class="bi bi-plus-slash-minus"></i></a></li>
                        <li class="nav-r"><a href="{% url 'cart:cart_detail' %}"><i class="bi bi-cart3"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </header>


    {% block content %}
    {% endblock %}

</body>

</html>

main/templates/main/product_detail.html
{% extends 'main/layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}

<div class="detail-product">
    <div class="product-info">
        <div>
            <ul>
                <li><a href="{% url 'main' %}"><img src="{% static 'main/img/70083.png' %}" alt="photo-home"> </a></li>
                <li><a href="{% url 'category' product.category.url %}">{{ product.category.name }}</a></li>
            </ul>
        </div>
        <h4>{{ product.name }}</h4>


        <form action="{% url 'add_rating' %}" method="post" name="rating">
            <b>{% trans 'Рейтинг' %}: </b>
            {% csrf_token %}
            <input type="hidden" value="{{ product.id }}" name="product">
            <span class="rating">
                {% for k, v in star_form.fields.star.choices %}
                {% if request.POST.star %}
                <p>Вы установили рейтинг: {{ request.POST.star }} из {{ star_form.fields.star.choices|length }}
                    возможных.</p>
                {% endif %}
                <input id="rating{{ v }}" type="radio" name="star" value="{{ k }}">
                <label for="rating{{ v }}">{{ k }}</label>
                {% endfor %}
            </span>
        </form>



        <p class="code">{% trans 'Код' %}: {{ product.code }}</p>
    </div>
    <div class="product-content">
        <div class="product-image">
            <img src="{{ product.image.url }}" alt="product-photo">
        </div>
        <div class="product-description">
            <hr>
            <p><b>{% trans 'Продавец' %}: </b><img src="{{ product.salesman.image.url }}" alt="photo-salesman"></p>
            <hr>

            <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="quantity" value="1">
                <input type="hidden" name="update" value="false">
                <button id="add-to-cart-button" class="btn btn-success" value="submit">
                    <i class="bi bi-cart3"></i> В корзину
                </button><br><br>
            </form>
            <form action="{% url 'compare' %}" method="get">
                <input type="hidden" name="product_ids" value="{{ product.id }}">
                <button type="submit">Добавить в сравнение</button>
              </form>
              


            <h5>{% trans 'Есть в наличии' %}</h5>
            <a href="#"><img src="{% static 'main/img/503011.png' %}" alt="photo-comparison"></a>
            <a href="#"><img src="{% static 'main/img/yellow-heart.png' %}" alt="photo-heard"></a>
        </div>
    </div>
    <div class="features">
        <h3>{% trans 'Характеристики' %}:</h3>

        {% if product.series %}
        <p>{% trans 'Серия' %}: {{ product.series }}</p>
        {% endif %}

        {% if product.display_size %}
        <p>{% trans 'Размер дисплея' %}: {{ product.display_size }}</p>
        {% endif %}

        {% if product.main_camera %}
        <p>{% trans 'Основная камера' %}: {{ product.main_camera }}</p>
        {% endif %}

        {% if product.fridge_capacity %}
        <p>{% trans 'Объем холодильной камеры, л' %}: {{ product.fridge_capacity }}</p>
        {% endif %}

        {% if product.weight %}
        <p>{% trans 'Вес' %}: {{ product.weight }} кг</p>
        {% endif %}

        {% if product.color %}
        <p>{% trans 'Цвет' %}: {{ product.color }}</p>
        {% endif %}

        {% if product.maximum_laundry_load %}
        <p>{% trans 'Загрузка' %}: {{ product.maximum_laundry_load }}</p>
        {% endif %}

        {% if product.spin_speed %}
        <p>{% trans 'Скорость отжима' %}: {{ product.spin_speed }}</p>
        {% endif %}

        {% if product.battery_capacity %}
        <p>{% trans 'Ёмкость батареи' %}: {{ product.battery_capacity }}</p>
        {% endif %}

        {% if product.CPU %}
        <p>{% trans 'Процессор' %}: {{ product.CPU }}</p>
        {% endif %}

        {% if product.ram %}
        <p>{% trans 'Оперативная память' %}: {{ product.ram }}</p>
        {% endif %}

        {% if product.operating_system %}
        <p>{% trans 'Операционная система' %}: {{ product.operating_system }}</p>
        {% endif %}

        {% if product.screen_refresh_rate %}
        <p>{% trans 'Частота обновления экрана' %}: {{ product.screen_refresh_rate }}</p>
        {% endif %}

        {% if product.ram_type %}
        <p>{% trans 'Тип оперативной памяти' %}: {{ product.ram_type }}</p>
        {% endif %}

        {% if product.ssd_capacity %}
        <p>{% trans 'Объём SSD' %}: {{ product.ssd_capacity }}</p>
        {% endif %}
    </div>
    <hr>
    <div class="add-review">
        <form action="{% url 'review' product.id %}" method="post" class="form">
            <h3>{% trans 'Оставить отзыв о товаре' %}</h3>
            {% csrf_token %}
            <div class="text">
                <label for="username"></label>
                <input type="text" name="name" placeholder="Имя *">
            </div><br>

            <div class="email">
                <label for="useremail"></label>
                <input type="email" name="email" placeholder="Email *">
            </div><br>

            <div class="text-user">
                <label for="review"></label>
                <textarea name="text" cols="23" rows="7" placeholder="Отзыв о товаре *"></textarea>
            </div><br>

            <div class="button">
                <button type="submit" class="btn btn-success">{% trans 'Отправить' %}</button>
            </div>
        </form>
        <div class="comments-user">
            <h3>{% trans 'Отзыв о товаре' %}:</h3>
            {% for review in product.review_set.all %}
            <p><b>{% trans 'Имя' %} :</b> {{ review.name }}</p>
            <p><b>{% trans 'Коментарий' %} :</b> {{ review.text }}</p>
            <hr>
            {% endfor %}
        </div>
    </div>
</div>

<script>
    const rating = document.querySelector('form[name=rating]');

    rating.addEventListener("change", function (e) {
        // Получаем данные из формы
        let data = new FormData(this);
        fetch(`${this.action}`, {
            method: 'POST',
            body: data
        })
            .then(response => {
                if (response.status === 201) {
                    // Сохраняем значение рейтинга в cookie
                    const selectedRating = document.querySelector('input[name=star]:checked').value;
                    document.cookie = `rating=${selectedRating}; expires=Fri, 31 Dec 9999 23:59:59 GMT`;
                    alert("Рейтинг установлен");
                } else {
                    alert("Ошибка");
                }
            })
            .catch(error => alert("Ошибка"));
    });
    document.addEventListener("DOMContentLoaded", function () {
        // Восстанавливаем значение рейтинга из cookie
        const cookieValue = document.cookie
            .split('; ')
            .find(row => row.startsWith('rating='))
            ?.split('=')[1];
        if (cookieValue) {
            const ratingInputs = document.querySelectorAll('input[name=star]');
            ratingInputs.forEach(input => {
                if (input.value === cookieValue) {
                    input.checked = true;
                }
            });
        }
    });
</script>


{% endblock %}